repos:
- repo: local
  hooks:
    - id: codespell
      name: Spell Checker (backend and frontend)
      language: system
      entry: codespell
      stages: [ pre-commit ]
    - id: ruff
      name: Ruff Formatter
      language: system
      entry: ruff format --force-exclude
      types_or: [python, pyi, jupyter]
      stages: [ pre-commit ]
      require_serial: true
    - id: ruff
      name: Ruff Linter
      language: system
      entry: ruff check --force-exclude
      args: [ "--fix" ] # Automatically fix issues
      types_or: [python, pyi, jupyter]
      stages: [ pre-commit ]
      require_serial: true
    - id: mypy
      name: Mypy Type Checker
      language: system
      entry: mypy
      types_or: [python, pyi, jupyter]
      stages: [ pre-commit ]
      require_serial: true
    - id: pytest
      name: pytest
      entry: pytest tests
      language: system
      types: [ python ]
      pass_filenames: false
      always_run: true